# Generated by Django 2.0 on 2022-07-20 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
